### ISSUE TITLE
Rebuilding instructions in viaq-template/README.md don't work

### ISSUE THREAD

**Issue by spbnick** [BitScoutOrg/elasticsearch-templates#19]
While trying to use the template-rebuilding command in `viaq-template/README.md`:

    python ../scripts/generate_template.py . com.redhat.viaq-template

The following error is produced:

    Traceback (most recent call last):
      File "../scripts/generate_template.py", line 230, in <module>
        input_template = open(definition_path, 'r')
    IOError: [Errno 21] Is a directory: '.'

REAMDE.md needs to be fixed to mention correct command.

**Comment by t0ffel** [comment]
done in https://github.com/ViaQ/elasticsearch-templates/pull/26
