### ISSUE TITLE
viaq-jenkins/README.md and viaq-template/README.md are duplicates

### ISSUE THREAD

**Issue by spbnick** [BitScoutOrg/elasticsearch-templates#23]
The `viaq-jenkins/README.md` and `viaq-template/README.md` files are mostly duplicates. This easily leads to confusion and they will likely go out of sync soon (they're already drifting apart).

Consider moving their contents to the top README.md, generalizing it accordingly.

**Comment by t0ffel** [comment]
done in https://github.com/ViaQ/elasticsearch-templates/pull/26
