### ISSUE TITLE
Consider removing generated files from the repo

### ISSUE THREAD

**Issue by spbnick** [BitScoutOrg/elasticsearch-templates#24]
Please consider removing generated files from the Git repository.

Keeping generated files in Git repository and history creates opportunity for abuse, confusion, and mistakes. It becomes tempting to hand-edit the generated files when the generation doesn't seem to work quite right, neglecting the original issue and leading to even more broken generation process. An opportunity to test generation more often is lost, as most of the time the generated files are fetched from Git, but when the need to run generation arises it turns out to be broken. It is a general practice to not keep generated files in a VCS, so newcomers can get confused which data is authoritative: the generation source or the generated product, and why the generation scripts are even needed.

**Comment by t0ffel** [comment]
@portante @richm please provide your feedback on this.

I generally like keeping generated files in repo as a matter of convenience.

**Comment by portante** [comment]
As a rule I am not in favor of keeping generated files in a repo.  Having clear scripts on how to generate them, or a single command (like `make`) is much preferable.

**Comment by spbnick** [comment]
I agree that keeping generated files in the repo is convenient in some cases. However, my point is: that convenience is outweighed by potential issues and difficulties. E.g. another one is forgetting to run generation after changing the source files and committing them.

**Comment by richm** [comment]
Looks like if we make a real "release" we can have a place to put non-version controlled files, that are built from our version controlled files.  For example, see https://github.com/openshift/origin/releases - the file https://github.com/openshift/origin/releases/download/v1.5.0-alpha.1/CHECKSUM.  I'm assuming if we do the same, we can have a link like https://github.com/ViaQ/elasticsearch-templates/releases/download/$version/filename.  What else should we do before we make an official release e.g. 0.0.1?

**Comment by richm** [comment]
So when you create a release, you can specify files to attach which can be downloaded from the release.  See https://github.com/ViaQ/elasticsearch-templates/releases/tag/0.0.1

I propose a release process like this:

* make changes, commit push
* tag the release `git tag 0.0.2` - push the tag
* generate any template .json files, docs, index pattern config files, whatever - the point is that these generated files must be generated with code/configs that has already been tagged and pushed
* Go to the `Releases` tab https://github.com/ViaQ/elasticsearch-templates/releases
* Press the `Draft a new release` button
* Fill in the information - use the pushed tag as the release
* Attach the generated files

Does this work for everyone?

**Comment by spbnick** [comment]
@richm, that's what I'd like to see.

**Comment by richm** [comment]
https://github.com/ViaQ/elasticsearch-templates/commit/a4447f97e23f0c98c114c67339525a928691955f
