### ISSUE TITLE
Makefile in viaq-template doesn't work

### ISSUE THREAD

**Issue by spbnick** [BitScoutOrg/elasticsearch-templates#25]
The following output is produced and no files are generated when running `make` in `viaq-template` directory:

	python ../scripts/generate_template.py . com.redhat.viaq
	Traceback (most recent call last):
	  File "../scripts/generate_template.py", line 230, in <module>
		input_template = open(definition_path, 'r')
	IOError: [Errno 21] Is a directory: '.'
	Makefile:7: recipe for target 'com.redhat.viaq.template.json' failed
	make: *** [com.redhat.viaq.template.json] Error 1

**Comment by spbnick** [comment]
I would like this fixed before I proceed with writing the tlog and aushape mappings, as I would like to test them, and without generation working I can't really do that. Thank you.

**Comment by spbnick** [comment]
Are there any news on this, ETA? I need this to work on tlog and aushape mappings. Thank you.

**Comment by t0ffel** [comment]
should be working now

**Comment by spbnick** [comment]
Thanks a lot, Anton!
