### ISSUE TITLE
clarify level field possible values

### ISSUE THREAD

**Issue by richm** [BitScoutOrg/elasticsearch-templates#35]
For example, the journald PRIORITY field has these syslog numeric values:
```
#define LOG_EMERG       0       /* system is unusable */
#define LOG_ALERT       1       /* action must be taken immediately */
#define LOG_CRIT        2       /* critical conditions */
#define LOG_ERR         3       /* error conditions */
#define LOG_WARNING     4       /* warning conditions */
#define LOG_NOTICE      5       /* normal but significant condition */
#define LOG_INFO        6       /* informational */
#define LOG_DEBUG       7       /* debug-level messages */
```
The `level` field is defined as a string: https://github.com/ViaQ/elasticsearch-templates/blob/master/namespaces/_default_.yml#L60

> Possible values: trace, crit, alert, emerg

How should the syslog numeric level be translated to a string?  For example: PRIORITY=0 is level=emerg ?

**Comment by richm** [comment]
should we use the number to string mapping used by syslog?
```CODE prioritynames[] =
  {
    { "alert", LOG_ALERT },
    { "crit", LOG_CRIT },
    { "debug", LOG_DEBUG },
    { "emerg", LOG_EMERG },
    { "err", LOG_ERR },
    { "error", LOG_ERR },               /* DEPRECATED */
    { "info", LOG_INFO },
    { "none", INTERNAL_NOPRI },         /* INTERNAL */
    { "notice", LOG_NOTICE },
    { "panic", LOG_EMERG },             /* DEPRECATED */
    { "warn", LOG_WARNING },            /* DEPRECATED */
    { "warning", LOG_WARNING },
    { NULL, -1 }
  };
```

**Comment by portante** [comment]
@richm, yes, we have been using the syslog defined name to number mapping. See [RFC 5424](https://tools.ietf.org/html/rfc5424), Page 10.  However, for the names, we default to using the rsyslog names for those numbers, where it makes sense.

Note that systemd/journald also uses the same mapping.

When translating from other non-syslog related levels, we map similar strings to the syslog ones (e.g. [Log4J's](https://logging.apache.org/log4j/2.0/manual/customloglevels.html) `FATAL` to `crit`).

**Comment by richm** [comment]
@portante @t0ffel ok - Anton, are you working on this?

**Comment by richm** [comment]
Fixed by https://github.com/ViaQ/elasticsearch-templates/commit/d88adda22793a683850276bda996be7a29b92e60
