### ISSUE TITLE
Support for multiple ES versions

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#71]
We want to support multiple versions of target ES (and related Kibana). The idea is that the code will produce distinct index templates, Kibana index patterns and asciidoc documentation for the fields based on the common templates for all supported ES versions.

Related issue: #70

**Comment by richm** [comment]
not asciidoc documentation - afaik there is nothing es 2.x or 5.x specific about the documentation.

**Comment by lukas-vlcek** [comment]
What if there will be at some point in the future? I think it does not hurt if we make it general and generate docs for each supported data model or ES version. WDYT?

**Comment by richm** [comment]
> What if there will be at some point in the future? I think it does not hurt if we make it general and generate docs for each supported data model or ES version. WDYT?

I think it makes things a lot more complicated for doc writers and end users to have two completely different sets of documentation.  I would rather not solve a problem that we do not yet have.

**Comment by lukas-vlcek** [comment]
Sure. I was looking into the code and I think we can start generating distinct doc sets per supported version only once we really need this option.
