### ISSUE TITLE
Change order of "string" related dynamic templates

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#83]
It seems that order of "string" related dynamic templates in our [skeleton.json](https://github.com/ViaQ/elasticsearch-templates/blob/12cb6938db6d6069d171502e9e38a97551183338/templates/skeleton.json) is incorrect. Namely those `aushape*` related.

Templates are [processed in order](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/dynamic-templates.html) thus I wonder what was the idea of adding `aushape*` templates after the generic [`"string_fields"`](https://github.com/ViaQ/elasticsearch-templates/blob/12cb6938db6d6069d171502e9e38a97551183338/templates/skeleton.json#L22-L37). If I understand it correctly then if ES will recognize any field in `aushape.data.*` or `aushape.data.*.*` or `aushape.data.*.*.*` as string then all the `aushape*` dynamic templates will be ignored because the `"string_fields"` template will win first.

I believe we need to move the generic `"string_fields"` to the end (ie. down).

**Comment by richm** [comment]
> Templates are processed in order thus I wonder what was the idea of adding aushape* templates after the generic "string_fields".

We probably just didn't understand how they would be processed.  So yes, let's fix it.

**Comment by spbnick** [comment]
Thanks guys!
