### ISSUE TITLE
Add `.all` alias to all project and operation indices

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#87]
Part of [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-templates.html) can configuration of [index aliases](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-aliases.html).

IIRC @jcantrill ask if we can have ES create an `_all` alias for every new `project.*` and `.operation.*` index automatically. We can do that by adding the following to the respective index templates:

```json
  "aliases": {
    "_all": {}
  }
```

@jcantrill Is this what you were after?

//cc @richm @ewolinetz

**Comment by ewolinetz** [comment]
@lukas-vlcek yes, however it should be `.all`
https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/master/src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java#L67

**Comment by lukas-vlcek** [comment]
@ewolinetz @jcantrill @richm Would it make more sense to make it configurable? Meaning the alias would not be hardcoded in index template but it would be responsibility of Aggregation Logging installation script to add needed aliases into index templates before they are pushed into ES.

One argument to support this approach: Currently the data model lives sort of "independently" and knows nothing about `.all` alias. It is the Aggregation Logging (specific EFK stack setup and use) that knows what the `.all` alias is used for and how it is called. If we decide to rename this alias in the future then all the changes can happen only in Aggregation Logging code (repo) independently of common data model.

WDYT?

**Comment by ewolinetz** [comment]
From the point making it future proof, it would make sense that it could be configured. However, I'm not sure we would have a case to ever change it...  To me `.all` shouldn't need to change given its purpose, the exception being maybe that we need to `s/\./_/`

**Comment by jcantrill** [comment]
I like the idea of configurability but I don't see a case where we would change it nor would we desire to add more aliases for 'every' index.  I would defer to hard coding it now and then we should remove from our plugin

**Comment by lukas-vlcek** [comment]
@ewolinetz thanks, I update the title accordingly (`s/_all/\.all/`)

**Comment by lukas-vlcek** [comment]
After this PR #88 is merged the alias `.all` will be part of index templates for both ES 2.x and ES 5.x. 

This means that if we do a new common data model release (including this change) we need to be sure there are appropriate modifications in aggregated logging code too (as long as we want to use new common data model release). //cc @jcantrill 

@richm What is the process of preparing a new common data model release?
