### ISSUE TITLE
Documentation file per supported ES version

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#89]
I noticed that the `*.asciidoc` files did change after we upgraded to ES5x due to new field type names in some cases. See https://github.com/openshift/origin-aggregated-logging/pull/922 for details.

I think the only changes in the documentation we can expect are the field type names (like `string` -> `keyword`/`text`, or `string` -> `ipv6`). Such changes should be rare IMO.

Originally we decided that the Common Data Model scripts will NOT generate multiple documentation files (one per ES version); see https://github.com/ViaQ/elasticsearch-templates/issues/71. I am not sure if this is a big issue or not. Shall we be concerned?

//cc @richm

**Comment by richm** [comment]
No, we should not be concerned as long as the differences are minor as described above.

**Comment by lukas-vlcek** [comment]
How are the documentation files generated in this project used? Are they included into some other documentation or something like that?

**Comment by richm** [comment]
https://docs.openshift.org/latest/install_config/aggregate_logging.html#exported-fields
and
https://github.com/openshift/origin-aggregated-logging/tree/master/docs

**Comment by lukas-vlcek** [comment]
As for the first link - it seems the documentation found there does not render the field `type` value in any way. And unless there is no future plan to do so then we can ignore concerns about the change in `type` value now.

As for the later link - the `hack/update-viaq-data-model.sh` script updates those files automatically, see https://github.com/openshift/origin-aggregated-logging/pull/961

Closing the ticket.
