### ISSUE TITLE
Use new index name template format

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#9]
According to proposed ElasticSearch Index structure index names should follow the following naming schema:

Tenant’s Versioned Index Names (not exposed):

```
openshift_<namespace_name>_<namespace_id>-v<version>-YYYY.MM.DD
```

Tenant’s Index Alias Names (exposed):

```
openshift_<namespace_name>_<namespace_id>-YYYY.MM.DD
```

Operational Index Names (not exposed):

```
openshift_operations-YYYY.MM.DD
```

This schema is not currently followed in skeletons (for example here: https://github.com/ViaQ/elasticsearch-templates/blob/master/viaq-openshift/skeleton.json#L47)

**Comment by t0ffel** [comment]
According to the discussion on irc w/ @richm the index names should be:
`.operations.YYYY.MM.DD` - for ops index. (same as old)
`project.<projectname>.<projectid>.YYYY.MM.DD` - for tenant's index. (old: `<projectname>.<projectid>.YYYY.MM.DD`)

CC @portante @lukas-vlcek

**Comment by lukas-vlcek** [comment]
We can close this ticket now? It seems obsolete to me.
