### ISSUE TITLE
ES5/Kibana5 - error - Unknown field type "keyword" for field "@timestamp.raw" in indexPattern ".all"

### ISSUE THREAD

**Issue by richm** [BitScoutOrg/elasticsearch-templates#91]
Unknown field type "keyword" for field "@timestamp.raw" in indexPattern ".all"
I think the problem is that the index pattern should use the _kibana_ type for the field not the _es_ type: https://github.com/elastic/kibana/blob/5.5/src/utils/kbn_field_types.js

Instead of 
```
\"@timestamp.raw\", \"searchable\": true, \"aggregatable\": true, \"readFromDocValues\": true, \"type\": \"keyword\", 
```
The index pattern file should use type string:
```
\"@timestamp.raw\", \"searchable\": true, \"aggregatable\": true, \"readFromDocValues\": true, \"type\": \"string\", 
```

**Comment by richm** [comment]
@lukas-vlcek

**Comment by lukas-vlcek** [comment]
@richm When exactly do you get this error? I am confused about how the `... indexPattern ".all"` part fits in.

Seems we will need to review logic here: https://github.com/ViaQ/elasticsearch-templates/blob/0db4a9324a3bd40a46a39c51ace532bfddcab13b/scripts/generate_template.py#L255-L270

**Comment by lukas-vlcek** [comment]
@richm @jcantrill Do you think you can point me to specific code that pushes index-pattern to ES5.x? Is it under https://github.com/jcantrill/openshift-elasticsearch-plugin/tree/5.5.0.x ?

**Comment by lukas-vlcek** [comment]
Or is the logic to push the index pattern under the `.all` type only here?
https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/utils/es_load_kibana_ui_objects#L41-L50

(It would require `$INDEX_PATTERN` to be set to `.all`)

**Comment by richm** [comment]
@lukas-vlcek https://github.com/jcantrill/openshift-elasticsearch-plugin/blob/5.5.0.x/src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java#L77

**Comment by lukas-vlcek** [comment]
@richm And it seems that this code leads to https://github.com/jcantrill/openshift-elasticsearch-plugin/blob/5.5.0.x/src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java#L164 which is exactly what I was looking for. Thanks!

**Comment by lukas-vlcek** [comment]
Not only we are getting this error for all `"keyword"` field type usages in the index pattern but also for all `"text"` field types usages too.
